 - name: Get Device Inventory Information
    ilo_device:
      category: Chassis
      command: GetDeviceInventoryInfo
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
